# podman-compose-superset.yml
x-superset-image: &superset-image docker.io/apache/superset:latest
x-superset-volumes: &superset-volumes
  - ./superset_home:/app/superset_home
  - ./docker/pythonpath:/app/pythonpath

x-common-env: &common-env
  SUPERSET_ENV: production
  SUPERSET_LOAD_EXAMPLES: "no"
  DATABASE_DB: superset
  DATABASE_HOST: db
  DATABASE_PASSWORD: ${DB_PASSWORD:-superset}
  DATABASE_USER: superset
  DATABASE_PORT: 5432
  DATABASE_DIALECT: postgresql
  POSTGRES_DB: superset
  POSTGRES_USER: superset
  POSTGRES_PASSWORD: ${DB_PASSWORD:-superset}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  SUPERSET_SECRET_KEY: ${SECRET_KEY:-CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET}
  SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://superset:${DB_PASSWORD:-superset}@db:5432/superset"

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: superset_db
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: superset_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  superset-init:
    image: *superset-image
    container_name: superset_init
    depends_on:
      - db
      - redis
    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting for DB..." &&
        until python3 -c "import socket; s=socket.create_connection(('db',5432),2); s.close()" 2>/dev/null; do echo 'Waiting for DB...'; sleep 2; done &&
        echo "DB ready. Running migrations..." &&
        superset db upgrade &&
        superset fab create-admin \
          --username admin \
          --firstname Admin \
          --lastname User \
          --email admin@superset.local \
          --password ${ADMIN_PASSWORD:-admin} || true &&
        superset init &&
        echo "Init complete."
    environment:
      <<: *common-env
    volumes: *superset-volumes

  superset:
    image: *superset-image
    container_name: superset_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting for DB..." &&
        until python3 -c "import socket; s=socket.create_connection(('db',5432),2); s.close()" 2>/dev/null; do echo 'Waiting for DB...'; sleep 2; done &&
        sleep 15 &&
        echo "Starting Superset..." &&
        gunicorn \
          --bind 0.0.0.0:8088 \
          --workers 4 \
          --worker-class gthread \
          --threads 4 \
          --timeout 120 \
          --limit-request-line 8190 \
          "superset.app:create_app()"
    environment:
      <<: *common-env
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
    volumes: *superset-volumes

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command:
      - /bin/sh
      - -c
      - |
        until python3 -c "import socket; s=socket.create_connection(('db',5432),2); s.close()" 2>/dev/null; do echo 'Waiting for DB...'; sleep 2; done &&
        sleep 20 &&
        celery --app=superset.tasks.celery_app:app worker --pool=prefork --concurrency=4
    environment:
      <<: *common-env
    volumes: *superset-volumes

  superset-beat:
    image: *superset-image
    container_name: superset_beat
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command:
      - /bin/sh
      - -c
      - |
        until python3 -c "import socket; s=socket.create_connection(('db',5432),2); s.close()" 2>/dev/null; do echo 'Waiting for DB...'; sleep 2; done &&
        sleep 25 &&
        celery --app=superset.tasks.celery_app:app beat --pidfile /tmp/celerybeat.pid --schedule /tmp/celerybeat-schedule
    environment:
      <<: *common-env
    volumes: *superset-volumes

volumes:
  db_data:
  redis_data: