services:
  caddy:
    build: ./Caddy
    image: hyperset-caddy:latest
    container_name: hyperset-caddy
    ports:
      - "443:443"
      - "80:80"
    environment:
      - HYPERSET_DOMAIN=${HYPERSET_DOMAIN}
      - OPENWEBUI_SUBDOMAIN=${OPENWEBUI_SUBDOMAIN}
      - AUTH_CRYPTO_KEY=${AUTH_CRYPTO_KEY}
    env_file:
      - ./.env
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - ./Caddy/users.json:/data/users.json:Z
      - ./Portal:/Portal:Z
      - caddy_data:/data/caddy
      - caddy_config:/config
    networks:
      - hyperset-net
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: hyperset-open-webui
    #ports:
    #  - "3000:8080"
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-secret-key-change-me-in-production}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-true}
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Auth-Request-Email
      - WEBUI_AUTH_TRUSTED_NAME_HEADER=X-Auth-Request-User
      - ENABLE_LOGIN_FORM=false
      - WEBUI_AUTH_TRUSTED_GROUPS_HEADER=X-Auth-Request-Groups
      - OAUTH_ROLES_CLAIM=X-Auth-Request-Groups
      - OAUTH_ADMIN_ROLES=hyperset/admin
      - OAUTH_ALLOWED_ROLES=hyperset/user,hyperset/admin
    volumes:
      - ./Open-WebUI/open-webui-data:/app/backend/data:Z
      - ./Open-WebUI/Tools:/app/backend/data/tools
    networks:
      - hyperset-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  open-webui-data:
    driver: local

networks:
  hyperset-net:
    external: true
