services:
  caddy:
    build: ./Caddy
    image: hyperset-caddy:latest
    container_name: hyperset-caddy
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - ./Caddy/users.json:/data/users.json:Z
      - ./Portal:/Portal:Z
      - caddy_data:/data/caddy
      - caddy_config:/config
    networks:
      - hyperset-net
    restart: unless-stopped

  superset:
    image: docker.io/apache/superset:latest
    container_name: hyperset-superset
    env_file:
      - ./.env
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    volumes:
      - ./Superset/superset_config.py:/app/pythonpath/superset_config.py:Z
      - superset_home:/app/superset_home
    networks:
      - hyperset-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  superset_home:

networks:
  hyperset-net:
    external: true