services:
  caddy:
    build: ./Caddy
    image: hyperset-caddy:latest
    container_name: hyperset-caddy
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - ./Caddy/users.json:/data/users.json:Z
      - ./Portal:/Portal:Z
      - caddy_data:/data/caddy
      - caddy_config:/config
    networks:
      - hyperset-net
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: hyperset-open-webui
    ports:
      - "3000:8080"
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-secret-key-change-me-in-production}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-true}
    volumes:
      - ./Open-WebUI/open-webui-data:/app/backend/data:Z
    restart: unless-stopped 
volumes:
  caddy_data:
  caddy_config:
  open-webui-data:
    driver: local

networks:
  hyperset-net:
    external: true
