services:
  caddy:
    build: ./Caddy
    image: hyperset-caddy:latest
    container_name: hyperset-caddy
    ports:
      - "443:443"
      - "80:80"
    environment:
      - HYPERSET_DOMAIN=${HYPERSET_DOMAIN}
      - AUTH_CRYPTO_KEY=${AUTH_CRYPTO_KEY}
      - SUPERSET_UPSTREAM=${SUPERSET_UPSTREAM}
    env_file:
      - ./.env
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - ./Caddy/users.json:/data/users.json:Z
      - ./Caddy/bridge.js:/Caddy/bridge.js:Z
      - caddy_data:/data/caddy
      - caddy_config:/config
    networks:
      - hyperset-net
    restart: unless-stopped

  pages:
    build: ./Pages-Service
    image: hyperset-pages:latest
    container_name: hyperset-pages
    volumes:
      - ./Pages:/pages:Z
    networks:
      - hyperset-net
    restart: unless-stopped

  superset-mcp:
    build: ./Superset-MCP
    image: hyperset-superset-mcp:latest
    container_name: hyperset-superset-mcp
    environment:
      # Internal address Caddy reaches Superset at — reused so the MCP talks to the same instance
      - SUPERSET_BASE_URL=${SUPERSET_UPSTREAM}
      # Service account for AUTH_REMOTE_USER mode — set to a Superset admin username
      - SUPERSET_REMOTE_USER=${SUPERSET_MCP_USER}
      # Fallback: classic username/password (used if SUPERSET_REMOTE_USER is empty)
      - SUPERSET_USERNAME=${SUPERSET_MCP_USER}
      - SUPERSET_PASSWORD=${SUPERSET_MCP_PASSWORD}
    networks:
      - hyperset-net
    restart: unless-stopped

  portal:
    build:
      context: ./portal-app
      # Next.js webpack compilation is memory-hungry; shm_size gives it enough
      # shared memory and the NODE_OPTIONS env is set in the Dockerfile.
      shm_size: "256m"
    image: hyperset-portal:latest
    container_name: hyperset-portal
    ports:
      - "3000:3000"
    environment:
      - HYPERSET_DOMAIN=${HYPERSET_DOMAIN}
      - SUPERSET_PUBLIC_URL=${SUPERSET_PUBLIC_URL}
      - PAGES_PUBLIC_URL=${PAGES_PUBLIC_URL}
      - SUPERSET_MCP_URL=http://hyperset-superset-mcp:8000/mcp
      # User LLM API
      - CHAT_API_URL=${CHAT_API_URL:-https://api.openai.com/v1}
      - CHAT_API_KEY=${CHAT_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL:-gpt-4o}
      # Admin LLM API (default; overridable at runtime via Admin Settings UI)
      - ADMIN_API_URL=${ADMIN_API_URL:-https://api.openai.com/v1}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ADMIN_MODEL=${ADMIN_MODEL:-gpt-4o}
      # Session encryption key for admin settings storage
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/config"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - hyperset-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  hyperset-net:
    external: true
