# docker-compose.yml (compatible with podman-compose)
x-superset-image: &superset-image docker.io/apache/superset:latest
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  - ./Superset/home:/app/superset_home
  - ./Superset:/app/pythonpath

x-common-env: &common-env
  SUPERSET_ENV: production
  SUPERSET_LOAD_EXAMPLES: "no"
  DATABASE_DB: superset
  DATABASE_HOST: db
  DATABASE_PASSWORD: ${DB_PASSWORD:-superset}
  DATABASE_USER: superset
  DATABASE_PORT: 5432
  DATABASE_DIALECT: postgresql
  POSTGRES_DB: superset
  POSTGRES_USER: superset
  POSTGRES_PASSWORD: ${DB_PASSWORD:-superset}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  SUPERSET_SECRET_KEY: ${SECRET_KEY:-CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET}
  SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://superset:${DB_PASSWORD:-superset}@db:5432/superset"

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: superset_db
    restart: unless-stopped
    environment:
      <<: *common-env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: superset_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset-init:
    image: *superset-image
    container_name: superset_init
    command:
      - /bin/sh
      - -c
      - |
        superset db upgrade &&
        superset fab create-admin \
          --username admin \
          --firstname Admin \
          --lastname User \
          --email admin@superset.local \
          --password ${ADMIN_PASSWORD:-admin} &&
        superset init
    environment:
      <<: *common-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes: *superset-volumes

  superset:
    image: *superset-image
    container_name: superset_app
    restart: unless-stopped
    command: >
      gunicorn
        --bind 0.0.0.0:8088
        --workers 4
        --worker-class gthread
        --threads 4
        --timeout 120
        --limit-request-line 8190
        "superset.app:create_app()"
    environment:
      <<: *common-env
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    restart: unless-stopped
    command: celery --app=superset.tasks.celery_app:app worker --pool=prefork --concurrency=4
    environment:
      <<: *common-env
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes

  superset-beat:
    image: *superset-image
    container_name: superset_beat
    restart: unless-stopped
    command: celery --app=superset.tasks.celery_app:app beat --pidfile /tmp/celerybeat.pid --schedule /tmp/celerybeat-schedule
    environment:
      <<: *common-env
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes

volumes:
  db_data:
  redis_data: